<script>

  import Aire from './lib/Aire.svelte'
  import Caratula from './lib/Caratula.svelte'






</script>


<Caratula />







<main>
  <div id="lv_Authors">

    <div class="lv_authorsWrapper">
        <span class="lv_authorName">
            <a href="https://www.lavanguardia.com/autores/laura-arago.html" target="_blank">
                <h4>Laura Aragó</h4>

            </a>
        </span>






    </div>


  

  
  
  </div> <!-- END of authors + xxss -->

  <div class="lv_blocText">
  
    <p class="lv_Par">España se recalienta. La demanda de aire acondicionado para paliar el impacto de las altas temperaturas se ha duplicado en las últimas décadas. Lo que en los ochenta era una solución para los días más calurosos, ahora es una requisito para sobrellevar los veranos implacables. Las olas de calor no solo son más frecuentes y más intensas sino que además se alargan en el tiempo y pueden ocurrir desde inicios de primavera hasta finales de otoño. El efecto sobre la capacidad energética es directo: el uso de climatizador generalizado dispara la demanda de electricidad.</p>

    <p class="lv_Par">Este vertiginoso aumento sitúa a España entre los países de Europa que más ha crecido la necesidad de aire acondicionado, según una investigación entre Corrective Europe en colaboración con La Vanguardia. Y todavía lo hará más en los próximos años. La demanda de aire acondicionado en Europa podría cuadruplicarse a lo largo del siglo XXI si no se toman medidas para mitigar el cambio climático, según un estudio de la Real Sociedad Meteorológica británica. Ante un escenario de temperaturas más extremas y prolongadas, la amenaza de una sobrecarga en la red eléctrica se vuelve cada vez más probable durante estos episodios.</p>
    </div>
    <div id="g-20241016_AirEuropaMapa-box" class="ai2html">
      <!-- Generated by ai2html v0.65.2 - 2024-10-15 - 20:01 -->
      <!-- ai file: 20241016_AirEuropaMapa.ai -->
    
      <style type='text/css' media='screen,print'>
        #g-20241016_AirEuropaMapa-box .g-artboard {
          margin:0 auto;
        }
        #g-20241016_AirEuropaMapa-box .g-artboard p {
          margin:0;
        }
        .g-aiAbs {
          position:absolute;
        }
        .g-aiImg {
          display:block;
          width:100% !important;
        }
        .g-aiPointText p { white-space: nowrap; }
      </style>
    
      <style type='text/css' media='screen,print'>
        /* Custom CSS */
            #g-20241016_AirEuropaMapa-movil {
          display:block;
          max-width: 300px !important;
        }
        #g-20241016_AirEuropaMapa-escritorio1200,
        #g-20241016_AirEuropaMapa-escritorio,
        #g-20241016_AirEuropaMapa-tableta,
        #g-20241016_AirEuropaMapa-movil2{ 
          display:none;
          }
        @media (min-width:375px) {
          #g-20241016_AirEuropaMapa-movil{
            display: none;
          }
          #g-20241016_AirEuropaMapa-movil2{
            display:block;
          }
        }
        @media (min-width:414px) {
          #g-20241016_AirEuropaMapa-movil{
            display: none;
          }
          #g-20241016_AirEuropaMapa-movil2{
            display:block;
          }
        }
        @media (min-width:566px) {
          #g-20241016_AirEuropaMapa-movil2{
            display: none;
          }
          #g-20241016_AirEuropaMapa-tableta{
            display:block;
          }
        }
        @media (min-width:833px) {
          #g-20241016_AirEuropaMapa-tableta{
            display: none;
          }
          #g-20241016_AirEuropaMapa-escritorio{
            display:block;
          }
        }
        @media (min-width:1200px) {
          #g-20241016_AirEuropaMapa-escritorio{
            display: none;
          }
          #g-20241016_AirEuropaMapa-escritorio1200{
            display:block;	
          }
          #g-20241016_AirEuropaMapa-box {
            margin-left: 0;
            margin-right: 0;
          }
        } 
      </style>
    
      <!-- Artboard: movil -->
      <div id="g-20241016_AirEuropaMapa-movil" class="g-artboard g-artboard-v3" data-min-width='310' data-max-width='359'>
        <style type='text/css' media='screen,print'>
          #g-20241016_AirEuropaMapa-movil {
            position:relative;
            overflow:hidden;
            width:310px;
          }
          #g-20241016_AirEuropaMapa-movil p {
            font-family:Roboto,sans-serif;
            font-weight:400;
            font-size:12px;
            line-height:14px;
            filter:alpha(opacity=100);
            -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
            opacity:1;
            letter-spacing:0em;
            text-align:left;
            color:rgb(0,0,0);
            text-transform:none;
            padding-bottom:0;
            padding-top:0;
            mix-blend-mode:normal;
            font-style:normal;
          }
          #g-20241016_AirEuropaMapa-movil .g-pstyle0 {
            font-weight:700;
            font-size:15px;
            line-height:19px;
          }
          #g-20241016_AirEuropaMapa-movil .g-pstyle1 {
            font-size:9px;
            line-height:12px;
          }
          #g-20241016_AirEuropaMapa-movil .g-pstyle2 {
            font-size:9px;
            line-height:13px;
          }
          #g-20241016_AirEuropaMapa-movil .g-pstyle3 {
            font-weight:700;
            font-size:9px;
            line-height:10px;
          }
          #g-20241016_AirEuropaMapa-movil .g-cstyle0 {
            font-weight:700;
          }
        </style>
        <img id="g-ai0-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20241016_AirEuropaMapa/20241016_AirEuropaMapa-movil.jpg"/>
        <div id="g-ai0-1" class="g-ai2html-settings g-aiAbs" style="top:0.8241%;left:3.4999%;width:80.6452%;">
          <p class="g-pstyle0">La demanda de aire acondicionado se dispara en el sur de Europa</p>
        </div>
        <div id="g-ai0-2" class="g-ai2html-settings g-aiAbs" style="top:8.4059%;left:3.4994%;width:96.4516%;">
          <p>El valor de enfriamiento sirve para estimar el impacto que las altas temperaturas tienen sobre la demanda energética de un país</p>
        </div>
        <div id="g-ai0-3" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:17.4291%;margin-top:-6.7px;left:3.4993%;width:204px;">
          <p class="g-pstyle1">Aumento del valor de enfriamiento en grados/día</p>
        </div>
        <div id="g-ai0-4" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:21.1376%;margin-top:-7.2px;left:13.2158%;width:12px;">
          <p class="g-pstyle2">20</p>
        </div>
        <div id="g-ai0-5" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:21.1376%;margin-top:-7.2px;left:24.8038%;width:12px;">
          <p class="g-pstyle2">40</p>
        </div>
        <div id="g-ai0-6" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:21.1376%;margin-top:-7.2px;left:36.8211%;width:12px;">
          <p class="g-pstyle2">60</p>
        </div>
        <div id="g-ai0-7" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:21.1376%;margin-top:-7.2px;left:48.8592%;width:12px;">
          <p class="g-pstyle2">80</p>
        </div>
        <div id="g-ai0-8" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:21.1376%;margin-top:-7.2px;left:59.4285%;width:18px;">
          <p class="g-pstyle2">100</p>
        </div>
        <div id="g-ai0-9" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:21.1376%;margin-top:-7.2px;left:71.349%;width:18px;">
          <p class="g-pstyle2">200</p>
        </div>
        <div id="g-ai0-10" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:21.1376%;margin-top:-7.2px;left:83.063%;width:18px;">
          <p class="g-pstyle2">250</p>
        </div>
        <div id="g-ai0-11" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:43.6358%;margin-top:-5.7px;left:64.105%;width:46px;">
          <p class="g-pstyle3">Estocolmo</p>
        </div>
        <div id="g-ai0-12" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:55.5029%;margin-top:-5.7px;left:58.1171%;width:27px;">
          <p class="g-pstyle3">Berlín</p>
        </div>
        <div id="g-ai0-13" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:56.8215%;margin-top:-5.7px;left:30.7138%;width:36px;">
          <p class="g-pstyle3">Londres</p>
        </div>
        <div id="g-ai0-14" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:61.6013%;margin-top:-5.7px;left:35.005%;width:24px;">
          <p class="g-pstyle3">París</p>
        </div>
        <div id="g-ai0-15" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:62.4254%;margin-top:-5.7px;left:65.2513%;width:26px;">
          <p class="g-pstyle3">Viena</p>
        </div>
        <div id="g-ai0-16" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:65.0626%;margin-top:-5.7px;left:45.5237%;width:27px;">
          <p class="g-pstyle3">Berna</p>
        </div>
        <div id="g-ai0-17" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:66.546%;margin-top:-5.7px;left:65.0458%;width:32px;">
          <p class="g-pstyle3">Zagreb</p>
        </div>
        <div id="g-ai0-18" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:66.546%;margin-top:-5.7px;left:83.2439%;width:39px;">
          <p class="g-pstyle3">Bucarest</p>
        </div>
        <div id="g-ai0-19" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:74.4574%;margin-top:-5.7px;left:14.4275%;width:32px;">
          <p class="g-pstyle3">Madrid</p>
        </div>
        <div id="g-ai0-20" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:75.9408%;margin-top:-5.7px;left:54.0388%;width:26px;">
          <p class="g-pstyle3">Roma</p>
        </div>
        <div id="g-ai0-21" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:78.7428%;margin-top:-5.7px;left:2.943%;width:30px;">
          <p class="g-pstyle3">Lisboa</p>
        </div>
        <div id="g-ai0-22" class="g-ai2html-settings g-aiAbs" style="top:90.1575%;left:47.3062%;width:48.0645%;">
          <p><span class="g-cstyle0">Chipre. </span>Es el territorio europeo que ha registrado un mayor aumento</p>
        </div>
      </div>
    
      <!-- Artboard: movil2 -->
      <div id="g-20241016_AirEuropaMapa-movil2" class="g-artboard g-artboard-v3" data-min-width='360' data-max-width='565'>
        <style type='text/css' media='screen,print'>
          #g-20241016_AirEuropaMapa-movil2 {
            position:relative;
            overflow:hidden;
            width:360px;
          }
          #g-20241016_AirEuropaMapa-movil2 p {
            font-family:Roboto,sans-serif;
            font-weight:400;
            font-size:14px;
            line-height:17px;
            filter:alpha(opacity=100);
            -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
            opacity:1;
            letter-spacing:0em;
            text-align:left;
            color:rgb(0,0,0);
            text-transform:none;
            padding-bottom:0;
            padding-top:0;
            mix-blend-mode:normal;
            font-style:normal;
          }
          #g-20241016_AirEuropaMapa-movil2 .g-pstyle0 {
            font-weight:700;
            font-size:18px;
            line-height:22px;
          }
          #g-20241016_AirEuropaMapa-movil2 .g-pstyle1 {
            font-size:11px;
            line-height:14px;
          }
          #g-20241016_AirEuropaMapa-movil2 .g-pstyle2 {
            font-size:11px;
            line-height:15px;
          }
          #g-20241016_AirEuropaMapa-movil2 .g-pstyle3 {
            font-weight:700;
            font-size:11px;
            line-height:12px;
          }
          #g-20241016_AirEuropaMapa-movil2 .g-pstyle4 {
            font-size:13px;
            line-height:16px;
          }
          #g-20241016_AirEuropaMapa-movil2 .g-cstyle0 {
            font-weight:700;
          }
        </style>
        <img id="g-ai1-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20241016_AirEuropaMapa/20241016_AirEuropaMapa-movil2.jpg"/>
        <div id="g-ai1-1" class="g-ai2html-settings g-aiAbs" style="top:0.5477%;left:1.8055%;width:81.9444%;">
          <p class="g-pstyle0">La demanda de aire acondicionado se dispara en el sur de Europa</p>
        </div>
        <div id="g-ai1-2" class="g-ai2html-settings g-aiAbs" style="top:7.942%;left:1.805%;width:98.0556%;">
          <p>El valor de enfriamiento sirve para estimar el impacto que las altas temperaturas tienen sobre la demanda energética de un país</p>
        </div>
        <div id="g-ai1-3" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.8008%;margin-top:-7.7px;left:1.805%;width:241px;">
          <p class="g-pstyle1">Aumento del valor de enfriamiento en grados/día</p>
        </div>
        <div id="g-ai1-4" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:20.5664%;margin-top:-8.2px;left:11.688%;width:14px;">
          <p class="g-pstyle2">20</p>
        </div>
        <div id="g-ai1-5" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:20.5664%;margin-top:-8.2px;left:23.4746%;width:14px;">
          <p class="g-pstyle2">40</p>
        </div>
        <div id="g-ai1-6" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:20.5664%;margin-top:-8.2px;left:35.6979%;width:14px;">
          <p class="g-pstyle2">60</p>
        </div>
        <div id="g-ai1-7" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:20.5664%;margin-top:-8.2px;left:47.9424%;width:14px;">
          <p class="g-pstyle2">80</p>
        </div>
        <div id="g-ai1-8" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:20.5664%;margin-top:-8.2px;left:58.6927%;width:21px;">
          <p class="g-pstyle2">100</p>
        </div>
        <div id="g-ai1-9" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:20.5664%;margin-top:-8.2px;left:70.8175%;width:21px;">
          <p class="g-pstyle2">200</p>
        </div>
        <div id="g-ai1-10" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:20.5664%;margin-top:-8.2px;left:82.7324%;width:21px;">
          <p class="g-pstyle2">250</p>
        </div>
        <div id="g-ai1-11" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:42.6808%;margin-top:-6.7px;left:63.4494%;width:54px;">
          <p class="g-pstyle3">Estocolmo</p>
        </div>
        <div id="g-ai1-12" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:54.3198%;margin-top:-6.7px;left:57.3589%;width:31px;">
          <p class="g-pstyle3">Berlín</p>
        </div>
        <div id="g-ai1-13" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:55.5523%;margin-top:-6.7px;left:29.4859%;width:42px;">
          <p class="g-pstyle3">Londres</p>
        </div>
        <div id="g-ai1-14" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:60.2078%;margin-top:-6.7px;left:33.8507%;width:28px;">
          <p class="g-pstyle3">París</p>
        </div>
        <div id="g-ai1-15" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:61.0294%;margin-top:-6.7px;left:64.6154%;width:30px;">
          <p class="g-pstyle3">Viena</p>
        </div>
        <div id="g-ai1-16" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:63.6311%;margin-top:-6.7px;left:44.5496%;width:31px;">
          <p class="g-pstyle3">Berna</p>
        </div>
        <div id="g-ai1-17" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:65.0004%;margin-top:-6.7px;left:64.4063%;width:37px;">
          <p class="g-pstyle3">Zagreb</p>
        </div>
        <div id="g-ai1-18" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:65.1374%;margin-top:-6.7px;left:82.9163%;width:46px;">
          <p class="g-pstyle3">Bucarest</p>
        </div>
        <div id="g-ai1-19" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:72.8055%;margin-top:-6.7px;left:12.9204%;width:37px;">
          <p class="g-pstyle3">Madrid</p>
        </div>
        <div id="g-ai1-20" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:74.3117%;margin-top:-6.7px;left:53.2108%;width:31px;">
          <p class="g-pstyle3">Roma</p>
        </div>
        <div id="g-ai1-21" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:77.0503%;margin-top:-6.7px;left:1.2391%;width:35px;">
          <p class="g-pstyle3">Lisboa</p>
        </div>
        <div id="g-ai1-22" class="g-ai2html-settings g-aiAbs" style="top:88.1835%;left:56.6401%;width:42.7778%;">
          <p class="g-pstyle4"><span class="g-cstyle0">Chipre. </span>Es el territorio europeo que ha registrado un mayor aumento</p>
        </div>
      </div>
    
      <!-- Artboard: tableta -->
      <div id="g-20241016_AirEuropaMapa-tableta" class="g-artboard g-artboard-v3" data-min-width='566' data-max-width='832'>
        <style type='text/css' media='screen,print'>
          #g-20241016_AirEuropaMapa-tableta {
            position:relative;
            overflow:hidden;
            width:566px;
          }
          #g-20241016_AirEuropaMapa-tableta p {
            font-family:Roboto,sans-serif;
            font-weight:400;
            font-size:13px;
            line-height:16px;
            filter:alpha(opacity=100);
            -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
            opacity:1;
            letter-spacing:0em;
            text-align:left;
            color:rgb(0,0,0);
            text-transform:none;
            padding-bottom:0;
            padding-top:0;
            mix-blend-mode:normal;
            font-style:normal;
          }
          #g-20241016_AirEuropaMapa-tableta .g-pstyle0 {
            font-weight:700;
            font-size:18px;
            line-height:22px;
          }
          #g-20241016_AirEuropaMapa-tableta .g-pstyle1 {
            font-size:14px;
            line-height:17px;
          }
          #g-20241016_AirEuropaMapa-tableta .g-pstyle2 {
            font-size:11px;
            line-height:14px;
          }
          #g-20241016_AirEuropaMapa-tableta .g-pstyle3 {
            font-size:11px;
            line-height:15px;
          }
          #g-20241016_AirEuropaMapa-tableta .g-pstyle4 {
            font-weight:700;
            font-size:11px;
            line-height:11px;
          }
          #g-20241016_AirEuropaMapa-tableta .g-pstyle5 {
            font-weight:700;
            font-size:11px;
            line-height:11px;
            color:rgb(255,255,255);
          }
          #g-20241016_AirEuropaMapa-tableta .g-cstyle0 {
            font-weight:700;
          }
        </style>
        <img id="g-ai2-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20241016_AirEuropaMapa/20241016_AirEuropaMapa-tableta.jpg"/>
        <div id="g-ai2-1" class="g-ai2html-settings g-aiAbs" style="top:1.2385%;left:0.8582%;width:52.1201%;">
          <p class="g-pstyle0">La demanda de aire acondicionado se dispara en el sur de Europa</p>
        </div>
        <div id="g-ai2-2" class="g-ai2html-settings g-aiAbs" style="top:7.2057%;left:0.8579%;width:83.7456%;">
          <p class="g-pstyle1">El valor de enfriamiento sirve para estimar el impacto que las altas temperaturas tienen sobre la demanda energética de un país</p>
        </div>
        <div id="g-ai2-3" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:13.026%;margin-top:-7.7px;left:0.8579%;width:241px;">
          <p class="g-pstyle2">Aumento del valor de enfriamiento en grados/día</p>
        </div>
        <div id="g-ai2-4" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0096%;margin-top:-8.2px;left:6.1396%;width:14px;">
          <p class="g-pstyle3">20</p>
        </div>
        <div id="g-ai2-5" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0096%;margin-top:-8.2px;left:12.4378%;width:14px;">
          <p class="g-pstyle3">40</p>
        </div>
        <div id="g-ai2-6" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0096%;margin-top:-8.2px;left:18.9694%;width:14px;">
          <p class="g-pstyle3">60</p>
        </div>
        <div id="g-ai2-7" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0096%;margin-top:-8.2px;left:25.5121%;width:14px;">
          <p class="g-pstyle3">80</p>
        </div>
        <div id="g-ai2-8" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0096%;margin-top:-8.2px;left:31.2566%;width:21px;">
          <p class="g-pstyle3">100</p>
        </div>
        <div id="g-ai2-9" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0096%;margin-top:-8.2px;left:37.7352%;width:21px;">
          <p class="g-pstyle3">200</p>
        </div>
        <div id="g-ai2-10" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0096%;margin-top:-8.2px;left:44.1022%;width:21px;">
          <p class="g-pstyle3">250</p>
        </div>
        <div id="g-ai2-11" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:28.0567%;margin-top:-6.2px;left:64.8347%;width:54px;">
          <p class="g-pstyle4">Estocolmo</p>
        </div>
        <div id="g-ai2-12" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:43.3687%;margin-top:-6.2px;left:57.825%;width:31px;">
          <p class="g-pstyle4">Berlín</p>
        </div>
        <div id="g-ai2-13" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:44.7198%;margin-top:-6.2px;left:29.5378%;width:42px;">
          <p class="g-pstyle4">Londres</p>
        </div>
        <div id="g-ai2-14" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:51.1373%;margin-top:-6.2px;left:33.9549%;width:28px;">
          <p class="g-pstyle4">París</p>
        </div>
        <div id="g-ai2-15" class="g-ai2html-settings g-aiAbs" style="top:52.579%;left:0.9636%;width:24.3816%;">
          <p><span class="g-cstyle0">Murcia. </span>La novena provincia de Europa con un mayor aumento</p>
        </div>
        <div id="g-ai2-16" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:53.7269%;margin-top:-6.2px;left:60.7208%;width:30px;">
          <p class="g-pstyle5">Viena</p>
        </div>
        <div id="g-ai2-17" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:55.6409%;margin-top:-6.2px;left:45.296%;width:31px;">
          <p class="g-pstyle4">Berna</p>
        </div>
        <div id="g-ai2-18" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:57.3297%;margin-top:-6.2px;left:65.4153%;width:37px;">
          <p class="g-pstyle5">Zagreb</p>
        </div>
        <div id="g-ai2-19" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:58.1179%;margin-top:-6.2px;left:89.2575%;width:46px;">
          <p class="g-pstyle5">Bucarest</p>
        </div>
        <div id="g-ai2-20" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:62.734%;margin-top:-6.2px;left:84.6249%;width:28px;">
          <p class="g-pstyle5">Sofía</p>
        </div>
        <div id="g-ai2-21" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:66.562%;margin-top:-6.2px;left:57.8176%;width:31px;">
          <p class="g-pstyle5">Roma</p>
        </div>
        <div id="g-ai2-22" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:68.1382%;margin-top:-6.2px;left:15.6785%;width:37px;">
          <p class="g-pstyle5">Madrid</p>
        </div>
        <div id="g-ai2-23" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:69.8271%;margin-top:-6.2px;left:0.6108%;width:35px;">
          <p class="g-pstyle5">Lisboa</p>
        </div>
        <div id="g-ai2-24" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:73.7677%;margin-top:-6.2px;left:89.9839%;width:37px;">
          <p class="g-pstyle4">Atenas</p>
        </div>
        <div id="g-ai2-25" class="g-ai2html-settings g-aiAbs" style="top:80.9514%;left:29.1426%;width:28.0919%;">
          <p><span class="g-cstyle0">Mallorca. </span>El territorio de España que más ha incrementado la demanda</p>
        </div>
        <div id="g-ai2-26" class="g-ai2html-settings g-aiAbs" style="top:80.9514%;left:59.7681%;width:29.8587%;">
          <p><span class="g-cstyle0">Caltanissetta. </span>Esta región del sur de Sicilia es la que crece más de Italia</p>
        </div>
        <div id="g-ai2-27" class="g-ai2html-settings g-aiAbs" style="top:91.1969%;left:56.1093%;width:29.682%;">
          <p><span class="g-cstyle0">Chipre. </span>Es el territorio europeo que ha registrado un mayor aumento</p>
        </div>
      </div>
    
      <!-- Artboard: escritorio -->
      <div id="g-20241016_AirEuropaMapa-escritorio" class="g-artboard g-artboard-v3" data-min-width='833' data-max-width='1199'>
        <style type='text/css' media='screen,print'>
          #g-20241016_AirEuropaMapa-escritorio {
            position:relative;
            overflow:hidden;
            width:833px;
          }
          #g-20241016_AirEuropaMapa-escritorio p {
            font-family:Roboto,sans-serif;
            font-weight:400;
            font-size:14px;
            line-height:18px;
            filter:alpha(opacity=100);
            -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
            opacity:1;
            letter-spacing:0em;
            text-align:left;
            color:rgb(0,0,0);
            text-transform:none;
            padding-bottom:0;
            padding-top:0;
            mix-blend-mode:normal;
            font-style:normal;
          }
          #g-20241016_AirEuropaMapa-escritorio .g-pstyle0 {
            font-weight:700;
            font-size:18px;
            line-height:22px;
          }
          #g-20241016_AirEuropaMapa-escritorio .g-pstyle1 {
            line-height:17px;
          }
          #g-20241016_AirEuropaMapa-escritorio .g-pstyle2 {
            font-size:11px;
            line-height:14px;
          }
          #g-20241016_AirEuropaMapa-escritorio .g-pstyle3 {
            font-size:11px;
            line-height:15px;
          }
          #g-20241016_AirEuropaMapa-escritorio .g-pstyle4 {
            font-weight:700;
            font-size:12px;
            line-height:12px;
          }
          #g-20241016_AirEuropaMapa-escritorio .g-pstyle5 {
            font-weight:700;
            font-size:12px;
            line-height:12px;
            color:rgb(255,255,255);
          }
          #g-20241016_AirEuropaMapa-escritorio .g-cstyle0 {
            font-weight:700;
          }
        </style>
        <img id="g-ai3-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20241016_AirEuropaMapa/20241016_AirEuropaMapa-escritorio.jpg"/>
        <div id="g-ai3-1" class="g-ai2html-settings g-aiAbs" style="top:1.4588%;left:16.3595%;width:35.4142%;">
          <p class="g-pstyle0">La demanda de aire acondicionado se dispara en el sur de Europa</p>
        </div>
        <div id="g-ai3-2" class="g-ai2html-settings g-aiAbs" style="top:7.4062%;left:16.3593%;width:56.9028%;">
          <p class="g-pstyle1">El valor de enfriamiento sirve para estimar el impacto que las altas temperaturas tienen sobre la demanda energética de un país</p>
        </div>
        <div id="g-ai3-3" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:13.095%;margin-top:-7.7px;left:16.3593%;width:241px;">
          <p class="g-pstyle2">Aumento del valor de enfriamiento en grados/día</p>
        </div>
        <div id="g-ai3-4" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0687%;margin-top:-8.2px;left:19.9481%;width:14px;">
          <p class="g-pstyle3">20</p>
        </div>
        <div id="g-ai3-5" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0687%;margin-top:-8.2px;left:24.2275%;width:14px;">
          <p class="g-pstyle3">40</p>
        </div>
        <div id="g-ai3-6" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0687%;margin-top:-8.2px;left:28.6655%;width:14px;">
          <p class="g-pstyle3">60</p>
        </div>
        <div id="g-ai3-7" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0687%;margin-top:-8.2px;left:33.1111%;width:14px;">
          <p class="g-pstyle3">80</p>
        </div>
        <div id="g-ai3-8" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0687%;margin-top:-8.2px;left:37.0143%;width:21px;">
          <p class="g-pstyle3">100</p>
        </div>
        <div id="g-ai3-9" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0687%;margin-top:-8.2px;left:41.4165%;width:21px;">
          <p class="g-pstyle3">200</p>
        </div>
        <div id="g-ai3-10" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.0687%;margin-top:-8.2px;left:45.7425%;width:21px;">
          <p class="g-pstyle3">250</p>
        </div>
        <div id="g-ai3-11" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:33.4176%;margin-top:-6.8px;left:51.1309%;width:59px;">
          <p class="g-pstyle4">Estocolmo</p>
        </div>
        <div id="g-ai3-12" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:50.0255%;margin-top:-6.8px;left:45.9032%;width:34px;">
          <p class="g-pstyle4">Berlín</p>
        </div>
        <div id="g-ai3-13" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:51.5965%;margin-top:-6.8px;left:24.8073%;width:46px;">
          <p class="g-pstyle4">Londres</p>
        </div>
        <div id="g-ai3-14" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:58.666%;margin-top:-6.8px;left:28.1015%;width:30px;">
          <p class="g-pstyle4">París</p>
        </div>
        <div id="g-ai3-15" class="g-ai2html-settings g-aiAbs" style="top:60.1473%;left:2.6839%;width:18.1273%;">
          <p><span class="g-cstyle0">Murcia. </span>La novena provincia de Europa con un mayor aumento</p>
        </div>
        <div id="g-ai3-16" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:61.3592%;margin-top:-6.8px;left:48.0629%;width:33px;">
          <p class="g-pstyle5">Viena</p>
        </div>
        <div id="g-ai3-17" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:63.6035%;margin-top:-6.8px;left:36.5593%;width:34px;">
          <p class="g-pstyle4">Berna</p>
        </div>
        <div id="g-ai3-18" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:65.2867%;margin-top:-6.8px;left:51.5638%;width:40px;">
          <p class="g-pstyle5">Zagreb</p>
        </div>
        <div id="g-ai3-19" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:66.1844%;margin-top:-6.8px;left:69.3449%;width:50px;">
          <p class="g-pstyle5">Bucarest</p>
        </div>
        <div id="g-ai3-20" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:71.2341%;margin-top:-6.8px;left:65.8901%;width:30px;">
          <p class="g-pstyle5">Sofía</p>
        </div>
        <div id="g-ai3-21" class="g-ai2html-settings g-aiAbs" style="top:72.6032%;left:84.6677%;width:14.4058%;">
          <p><span class="g-cstyle0">Chipre. </span>Es el territorio europeo que ha registrado un mayor aumento</p>
        </div>
        <div id="g-ai3-22" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:75.4983%;margin-top:-6.8px;left:45.8978%;width:33px;">
          <p class="g-pstyle5">Roma</p>
        </div>
        <div id="g-ai3-23" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:77.1815%;margin-top:-6.8px;left:14.4714%;width:40px;">
          <p class="g-pstyle5">Madrid</p>
        </div>
        <div id="g-ai3-24" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:79.0892%;margin-top:-6.8px;left:2.155%;width:38px;">
          <p class="g-pstyle4">Lisboa</p>
        </div>
        <div id="g-ai3-25" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:83.2411%;margin-top:-6.8px;left:69.8867%;width:40px;">
          <p class="g-pstyle4">Atenas</p>
        </div>
        <div id="g-ai3-26" class="g-ai2html-settings g-aiAbs" style="top:91.1187%;left:24.5126%;width:21.0084%;">
          <p><span class="g-cstyle0">Mallorca. </span>El territorio de España que más ha incrementado la demanda</p>
        </div>
        <div id="g-ai3-27" class="g-ai2html-settings g-aiAbs" style="top:91.1187%;left:47.3524%;width:22.2089%;">
          <p><span class="g-cstyle0">Caltanissetta. </span>Esta región del sur de Sicilia es la que crece más de Italia</p>
        </div>
      </div>
    
      <!-- Artboard: escritorio1200 -->
      <div id="g-20241016_AirEuropaMapa-escritorio1200" class="g-artboard g-artboard-v3" data-min-width='1200'>
        <style type='text/css' media='screen,print'>
          #g-20241016_AirEuropaMapa-escritorio1200 {
            position:relative;
            overflow:hidden;
            width:1200px;
          }
          #g-20241016_AirEuropaMapa-escritorio1200 p {
            font-family:Roboto,sans-serif;
            font-weight:400;
            font-size:14px;
            line-height:18px;
            filter:alpha(opacity=100);
            -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
            opacity:1;
            letter-spacing:0em;
            text-align:left;
            color:rgb(0,0,0);
            text-transform:none;
            padding-bottom:0;
            padding-top:0;
            mix-blend-mode:normal;
            font-style:normal;
          }
          #g-20241016_AirEuropaMapa-escritorio1200 .g-pstyle0 {
            font-weight:700;
            font-size:18px;
            line-height:22px;
          }
          #g-20241016_AirEuropaMapa-escritorio1200 .g-pstyle1 {
            line-height:17px;
          }
          #g-20241016_AirEuropaMapa-escritorio1200 .g-pstyle2 {
            font-size:11px;
            line-height:14px;
          }
          #g-20241016_AirEuropaMapa-escritorio1200 .g-pstyle3 {
            font-size:11px;
            line-height:15px;
          }
          #g-20241016_AirEuropaMapa-escritorio1200 .g-pstyle4 {
            font-weight:700;
            font-size:12px;
            line-height:12px;
          }
          #g-20241016_AirEuropaMapa-escritorio1200 .g-pstyle5 {
            font-weight:700;
            font-size:12px;
            line-height:12px;
            color:rgb(255,255,255);
          }
          #g-20241016_AirEuropaMapa-escritorio1200 .g-cstyle0 {
            font-weight:700;
          }
        </style>
        <img id="g-ai4-0" class="g-aiImg" src="https://visuals.lavanguardia.com/ai2html/20241016_AirEuropaMapa/20241016_AirEuropaMapa-escritorio1200.jpg"/>
        <div id="g-ai4-1" class="g-ai2html-settings g-aiAbs" style="top:2.0277%;left:26.6947%;width:24.5833%;">
          <p class="g-pstyle0">La demanda de aire acondicionado se dispara en el sur de Europa</p>
        </div>
        <div id="g-ai4-2" class="g-ai2html-settings g-aiAbs" style="top:7.998%;left:26.6945%;width:39.5%;">
          <p class="g-pstyle1">El valor de enfriamiento sirve para estimar el impacto que las altas temperaturas tienen sobre la demanda energética de un país</p>
        </div>
        <div id="g-ai4-3" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:13.8215%;margin-top:-7.7px;left:26.6945%;width:241px;">
          <p class="g-pstyle2">Aumento del valor de enfriamiento en grados/día</p>
        </div>
        <div id="g-ai4-4" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.8066%;margin-top:-8.2px;left:29.1857%;width:14px;">
          <p class="g-pstyle3">20</p>
        </div>
        <div id="g-ai4-5" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.8066%;margin-top:-8.2px;left:32.1564%;width:14px;">
          <p class="g-pstyle3">40</p>
        </div>
        <div id="g-ai4-6" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.8066%;margin-top:-8.2px;left:35.2371%;width:14px;">
          <p class="g-pstyle3">60</p>
        </div>
        <div id="g-ai4-7" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.8066%;margin-top:-8.2px;left:38.3231%;width:14px;">
          <p class="g-pstyle3">80</p>
        </div>
        <div id="g-ai4-8" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.8066%;margin-top:-8.2px;left:41.0326%;width:21px;">
          <p class="g-pstyle3">100</p>
        </div>
        <div id="g-ai4-9" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.8066%;margin-top:-8.2px;left:44.0883%;width:21px;">
          <p class="g-pstyle3">200</p>
        </div>
        <div id="g-ai4-10" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:16.8066%;margin-top:-8.2px;left:47.0914%;width:21px;">
          <p class="g-pstyle3">250</p>
        </div>
        <div id="g-ai4-11" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:34.1099%;margin-top:-6.8px;left:50.8318%;width:59px;">
          <p class="g-pstyle4">Estocolmo</p>
        </div>
        <div id="g-ai4-12" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:50.7819%;margin-top:-6.8px;left:47.2029%;width:34px;">
          <p class="g-pstyle4">Berlín</p>
        </div>
        <div id="g-ai4-13" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:52.3589%;margin-top:-6.8px;left:32.5589%;width:46px;">
          <p class="g-pstyle4">Londres</p>
        </div>
        <div id="g-ai4-14" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:59.4558%;margin-top:-6.8px;left:34.8456%;width:30px;">
          <p class="g-pstyle4">París</p>
        </div>
        <div id="g-ai4-15" class="g-ai2html-settings g-aiAbs" style="top:60.9428%;left:17.2015%;width:12.5833%;">
          <p><span class="g-cstyle0">Murcia. </span>La novena provincia de Europa con un mayor aumento</p>
        </div>
        <div id="g-ai4-16" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:62.1593%;margin-top:-6.8px;left:48.7021%;width:33px;">
          <p class="g-pstyle5">Viena</p>
        </div>
        <div id="g-ai4-17" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:64.4123%;margin-top:-6.8px;left:40.7168%;width:34px;">
          <p class="g-pstyle4">Berna</p>
        </div>
        <div id="g-ai4-18" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:66.102%;margin-top:-6.8px;left:51.1324%;width:40px;">
          <p class="g-pstyle5">Zagreb</p>
        </div>
        <div id="g-ai4-19" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:67.1159%;margin-top:-6.8px;left:63.4754%;width:50px;">
          <p class="g-pstyle5">Bucarest</p>
        </div>
        <div id="g-ai4-20" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:72.0724%;margin-top:-6.8px;left:61.0772%;width:30px;">
          <p class="g-pstyle5">Sofía</p>
        </div>
        <div id="g-ai4-21" class="g-ai2html-settings g-aiAbs" style="top:73.8973%;left:74.959%;width:10.0833%;">
          <p><span class="g-cstyle0">Chipre. </span>Es el territorio europeo que ha registrado un mayor aumento</p>
        </div>
        <div id="g-ai4-22" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:76.353%;margin-top:-6.8px;left:47.1992%;width:33px;">
          <p class="g-pstyle5">Roma</p>
        </div>
        <div id="g-ai4-23" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:78.0428%;margin-top:-6.8px;left:25.3841%;width:40px;">
          <p class="g-pstyle5">Madrid</p>
        </div>
        <div id="g-ai4-24" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:79.9578%;margin-top:-6.8px;left:16.8344%;width:38px;">
          <p class="g-pstyle4">Lisboa</p>
        </div>
        <div id="g-ai4-25" class="g-ai2html-settings g-aiAbs g-aiPointText" style="top:84.2384%;margin-top:-6.8px;left:63.8515%;width:40px;">
          <p class="g-pstyle4">Atenas</p>
        </div>
        <div id="g-ai4-26" class="g-ai2html-settings g-aiAbs" style="top:92.0337%;left:27.0342%;width:19.1667%;">
          <p><span class="g-cstyle0">Mallorca. </span>El territorio de España que más ha incrementado la demanda</p>
        </div>
        <div id="g-ai4-27" class="g-ai2html-settings g-aiAbs" style="top:92.0337%;left:48.2089%;width:20.4167%;">
          <p><span class="g-cstyle0">Caltanissetta. </span>Esta región del sur de Sicilia es la que crece más de Italia</p>
        </div>
      </div>
      <!-- End ai2html - 2024-10-15 - 20:01 -->
    </div>
    
    <p class="lv_Par">El crecimiento se produce en todo el territorio europeo pero en términos absolutos los cambios más drásticos se registran en los países sureños que bordean el mediterráneo. España es después de Chipre, Malta, Grecia y Portugal, el quinto país de Europa que ha registrado un mayor aumento, según el valor de enfriamiento que elabora el Centro Común de Investigación de la Comisión Europea —JRC, por sus siglas en inglés—. Esta métrica sirve para estimar el impacto que las altas temperaturas tienen sobre la demanda energética de un país y técnicamente se expresa en grados día.
    </p>

    <p class="lv_Par">El cálculo parte de los 24°C, la temperatura veraniega de confort en la que no se necesita utilizar el aire acondicionado. Si un día la temperatura media es de 30°C, significará que ese día hay 6°C de diferencia entre la temperatura de confort y la temperatura exterior. Si al cabo del año sumamos todos estos grados de más que ha habido respecto a la temperatura de confort obtendremos el esfuerzo de refrigeración que ha tenido que hacer todo el país en un año. Por ejemplo, España durante los años ochenta tenía una media de 153°C acumulados al año de refrigeración. En la última década ha tenido una media de 259°C. Significa que el esfuerzo de refrigeración que tiene que hacer el país para mantener sus edificios en una temperatura confortable se ha multiplicado por 1,7. 
    </p>


  <Aire />



  <div class="lv_blocText">
    <p class="lv_Par">Las diez regiones que registran un mayor incremento de grados acumulados se encuentran en Chipre, Italia, España y Grecia. En la península son las provincias del sur las que más lo han sufrido. Mallorca y Murcia no solo encabezan la lista estatal sino que también se encuentran entre las 10 zonas más afectadas de Europa. En Mallorca ha habido un crecimiento de 293 y en Murcia de 277 grados acumulados. 
    </p>

    <p class="lv_Par">La cuestión de fondo va más allá del confort térmico. En un país donde la red eléctrica ya se ve sometida a picos de demanda durante los meses más calurosos, el aumento en el uso de aire acondicionado podría convertirse en un riesgo para la estabilidad energética. Mientras que en invierno los edificios pueden calentarse utilizando diversas fuentes de energía, la refrigeración depende exclusivamente de la electricidad. Esta dependencia, combinada con temperaturas cada vez más extremas, está generando un desafío sin precedentes para las infraestructuras energéticas.
    </p>

    <p class="lv_Par">Según Dominic Royé, investigador de la Fundación para la Investigación del Clima, “los picos de consumo eléctrico durante los días de calor extremo son cada vez más frecuentes y suponen un problema real para la red energética. El riesgo de sobrecarga es cada vez mayor, y si no se toman medidas, podríamos enfrentarnos a apagones en momentos críticos”.
    </p>

    <p class="lv_Par">El patrón que se observa en España se extiende por toda Europa. También en el centro y norte del continente sufren las consecuencias.  En países como Alemania, Países Bajos o Suecia donde hasta hace pocas décadas la necesidad de aire acondicionado era mínima, los veranos  demandan cada vez más  sistemas de refrigeración   Esto supone un reto enorme estos países, que no cuentan con la infraestructura adecuada para soportar este tipo de demanda.
    </p>

    <p class="lv_Par">Europa es el continente que más rápido se está calentando del mundo y los países del sur son los más afectados. Según la Agencia Europea de Medio Ambiente, la temperatura en España desde los ochenta hasta ahora ha subido al menos 0,70°C y con ella la necesidad de refrigeración de los edificios. La intensidad promedio del calor en España en los últimos diez años ha sido similar a la de Ciudad Real en los años ochenta. De seguir con el ritmo de emisiones actuales, en el año 2100 se podría cuadruplicar la demanda de aire acondicionado actual.
    </p>

  </div>













  




  





  








  

  
</main>








<style>

main{
        padding:10px;
    }

p.lv_Par{
        font-family: 'TRegular', serif;
        -webkit-font-smoothing: antialiased;
        font-size: 18px;
        line-height: 27px;
        font-weight: 400;
        text-align: left;
        margin: 0 auto 20px auto;
        max-width: 550px;
        color: #2e2e2e;
        letter-spacing: -.1px;
        word-wrap: break-word;
    }
  

              #lv_Authors{
    
    padding-top: 20px;
    margin-bottom: 10px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;

  }

  .lv_authorsWrapper{

  }

  .lv_authorName{
    text-align: center;
  }

  .lv_authorName a{
      text-decoration: none;
      
  }

  .lv_authorName h4{
      text-transform: uppercase;
      color: #000000;
      font-family: 'HMedium', serif;
      font-size: 16px;

  }

  .lv_authorName h5{
      margin: 12px 0;
      text-transform: uppercase;
      color: #000000;
      font-family: 'HMedium', serif;
      font-size: 12px;

  }
</style>
